### ISSUE TITLE
Can't create controller (Atom 1.0.2)

### ISSUE THREAD

**Issue by falkolab** [m1ga/ti-create#3] opened 2015-07-27 07:05 UTC
```
The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 41.0.2272.76 and Node 1.5.1.

The packages listed should now ship versions of these native modules that are compatible with Node 1.5.1.
```

```
Listed below are the incompatible native modules that this package depends on.

pathwatcher@4.4.0
Error message: dlopen(/Users/falko/.atom/packages/ti-create/node_modules/pathwatcher/build/Release/pathwatcher.node, 1): no suitable image found. Did find: /Users/falko/.atom/packages/ti-create/node_modules/pathwatcher/build/Release/pathwatcher.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
runas@2.0.0
Error message: dlopen(/Users/falko/.atom/packages/ti-create/node_modules/pathwatcher/node_modules/runas/build/Release/runas.node, 1): no suitable image found. Did find: /Users/falko/.atom/packages/ti-create/node_modules/pathwatcher/node_modules/runas/build/Release/runas.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by nuno** [comment] 2015-07-27 13:43
yeah I can confirm the issue above.

**Comment by m1ga** [comment] 2015-07-27 16:30
Thanks, I'll have a look soon

**Comment by Dionysos211** [comment] 2015-08-06 09:03
These functions didn't work anymore..
Titanium -> Create:
-> Project (nothing happens)
-> Controller (Always shows: Doesn't look like an Alloy Project - But it is!!)
-> Widget (Always shows: Doesn't look like an Alloy Project - But it is!!)

What i did before to get off that error "incompatible native modules"
$ cd /Users/$USER/.atom/packages/ti-create
$ npm update

update the package.json to match the new versions

$ apm rebuild

after that the "incompatible native modules" error disappear..

but the module didn't work at all..

**Comment by Dionysos211** [comment] 2015-08-18 09:06
Some Testing...
First removed the comment before Line 13 in ti-create/lib/ti-create.js
then i figured out that there is an env problem in OS X because i get this error:
Uncaught BufferedProcessError: Failed to spawn command `titanium`. Make sure `titanium` is installed and on your PATH
if i start Atom from iTerm then the env ist loaded.. from launchpad or Doc i get this error..

ok startet from terminal works... AND i could successfully create a new Project..
but if i tried to create a Controller:
Doesn't look like an Alloy Project - But it is!!

**Comment by Dionysos211** [comment] 2015-08-18 09:25
Ok now all works.. xD i figured out you only check on the first Project Path:
var ppath = atom.project.getPaths()[0];

Workaround:
Do the things i wrote in my first Post to Update the Module and get off the "compatible" error
Go to /Users/$USER/.atom/packages/ti-create/lib/ti-create.js and Remove the Comment before Line 13
Check that you have the correct setup in your ~/.profile, ~/.bash_profile, ~/.bashrc, ~/.zshrc or launchd .. launchctl... 
open terminal.. if u can use the titanium command.. all fine.. open atom from terminal..
remove all Project paths..
add the Workspace path as a new Project Folder..
then go to Menue Packages -> Titanium -> Create -> Project
type in the Project name.. Enter
u get a Done notification
remove all Project Folders from the List..
Add the Created Project as a Project Folder..
Now u can create Controllers an Widgets.. and start working..

**Comment by m1ga** [comment] 2015-08-18 09:37
thanks for that! In fedora I still have an old node version so I couldn't test the first part and I had the ti command in my PATH so I wasn't able to catch that error :) I'll add a check before calling the command line!

**Comment by Dionysos211** [comment] 2015-08-18 14:05
I have tested 0.19 now.
Looks fine for me... everything works..

And my workaround above is no longer needed..
because the new window is fired up after creating a project in workspace.. 

the Only Problem i still have is the PATH error in case when starting atom from launchpad or Doc..
if i start atom from iTerm everything is fine.. from doc or Launchpad i get the error..
/usr/local/bin/titanium (symlink do global node_module)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Perhaps this is because i installed Atom via brew cask..i don't know..
still reading in: mvim `which atom`

there is something like:
open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
but i guess it didn't work propperly with an installation in /opt/homebrew-cask/Caskroom/atom

I will try something like this:
http://www.jochenhebbrecht.be/site/2015-04-14/mac/os-x-1010-yosemite-and-environment-variables

because of Atom Env problem in OS X and GUI apps..
see: https://discuss.atom.io/t/atom-command-doesnt-pass-environment-variables-to-atom/1596

and this maybe a solution explained in a other Plugin:
https://atom.io/packages/pandoc#problems-with-path

Another hint i found was:
1. Rename Atom.app/Contents/MacOS/Atom to Atom.bin
2. Create this script at Atom.app/Contents/MacOS/Atom

#!/usr/local/bin/bash -l
`dirname $0`/Atom.bin $@
chmod +x Atom.app/Contents/MacOS/Atom
Now it passes env for both terminal and launchpad. The -l flag does the trick.

**Comment by Dionysos211** [comment] 2015-08-18 15:32
Solution for that found here ($PATH` only present when Atom is launched from command line):
https://github.com/atom-community/linter/issues/150

Add this to init.coffee (CMD+,) open config Folder select init.coffee

process.env.PATH = ["/usr/bin",
                    "/usr/local/bin",
                    "/bin",
                    "/usr/sbin",
                    "/sbin"
                    process.env.PATH].join(":")

Now the $PATH get loaded even Atom is launched from Doc or Launchpad

**Comment by nuno** [comment] 2015-08-18 15:47
@Dionysos211  works finally for me too!
@m1ga Thanks to the update today, looks good!

**Comment by m1ga** [comment] 2015-08-18 15:50
:+1: then I close it. Be sure to follow https://github.com/yomybaby/atom-titanium which might include the create part too!

**Closed by m1ga** 2015-08-18 15:50 UTC
Labels: bug
